# Generated by Django 4.0.2 on 2022-02-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('wins', models.IntegerField(max_length=50)),
                ('losses', models.IntegerField(max_length=50)),
                ('draws', models.IntegerField(max_length=50)),
            ],
        ),
    ]
