# Generated by Django 4.0.2 on 2022-02-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='draws',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='players',
            name='losses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='players',
            name='wins',
            field=models.IntegerField(),
        ),
    ]
