# Generated by Django 4.0.2 on 2022-02-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_players_draws_alter_players_losses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='id',
        ),
        migrations.AddField(
            model_name='players',
            name='pid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
