# Generated by Django 4.0.2 on 2022-02-06 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_players_id_players_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='commanders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc', models.IntegerField()),
                ('color_identity', models.CharField(max_length=15)),
                ('loyalty', models.CharField(max_length=10, null=True)),
                ('power', models.CharField(max_length=10, null=True)),
                ('toughness', models.CharField(max_length=10, null=True)),
                ('typeLine', models.CharField(max_length=100)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.games')),
            ],
        ),
    ]
