# Generated by Django 4.0.2 on 2022-02-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_commanders'),
    ]

    operations = [
        migrations.CreateModel(
            name='comPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('pid', models.IntegerField()),
                ('times', models.IntegerField()),
                ('wins', models.IntegerField()),
            ],
        ),
    ]
