# Generated by Django 4.0.2 on 2022-02-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_complayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commanders',
            name='cname',
            field=models.CharField(max_length=50),
        ),
    ]
