# Generated by Django 4.0.2 on 2022-02-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_commanders_cname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commanders',
            name='cname',
            field=models.CharField(max_length=100),
        ),
    ]
