# Generated by Django 4.0.2 on 2022-02-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_commanders_cname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commanders',
            name='loyalty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='commanders',
            name='power',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='commanders',
            name='toughness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
