# Generated by Django 4.0.2 on 2022-04-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_commanders_loyalty_alter_commanders_power_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('gameid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=25)),
                ('p1', models.CharField(max_length=50)),
                ('p1c', models.CharField(max_length=50)),
                ('p2', models.CharField(max_length=50)),
                ('p2c', models.CharField(max_length=50)),
                ('p3', models.CharField(max_length=50)),
                ('p3c', models.CharField(max_length=50)),
                ('p4', models.CharField(max_length=50)),
                ('p4c', models.CharField(max_length=50)),
                ('winner', models.CharField(max_length=50)),
            ],
        ),
    ]
