# Generated by Django 4.0.2 on 2022-04-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_rename_games_season1game_rename_game_season2game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season2game',
            name='p1c',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='season2game',
            name='p2c',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='season2game',
            name='p3c',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='season2game',
            name='p4c',
            field=models.CharField(max_length=100),
        ),
    ]
